[phases.setup]
nixPkgs = [
    "python311Full",
    "python311Packages.pip",
    "python311Packages.setuptools",
    "python311Packages.wheel",
    "ffmpeg",
    "gcc",
    "glib",
    "libGL",
    "xorg.libX11",
    "xorg.libXext"
]

[phases.install]
cmds = [
    # Make sure PATH is correct
    "export PATH=$(dirname $(which python3.11)):$PATH",

    # Confirm pip is present
    "which pip3.11 || echo 'pip not found — linking manually...'",

    # Link pip globally
    "ln -sf $(which pip3.11) /usr/local/bin/pip || true",

    # Use pip directly instead of 'python -m pip'
    "pip install --upgrade pip setuptools wheel",

    # Install project dependencies
    "pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "python3.11 manage.py collectstatic --noinput || true"
]

[start]
cmd = "gunicorn myCapstone.wsgi:application"
