[phases.setup]
nixPkgs = [
    "python311Full",
    "ffmpeg",
    "gcc",
    "glib",
    "libGL",
    "xorg.libX11",
    "xorg.libXext"
]

[phases.install]
cmds = [
    # Make sure Python is on PATH
    "export PATH=$(dirname $(which python3.11)):$PATH",

    # Bootstrap pip manually if it's missing
    "python3.11 -m ensurepip --upgrade || true",
    "python3.11 -m pip install --upgrade pip setuptools wheel || true",

    # Install dependencies
    "python3.11 -m pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "python3.11 manage.py collectstatic --noinput || true"
]

[start]
cmd = "gunicorn myCapstone.wsgi:application"
