[phases.setup]
nixPkgs = [
  "python311",
  "gcc",
  "ffmpeg",
  "libsm",
  "libxext",
  "libgl1",
  "libglib2.0-0"
]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "gunicorn myCapstone.wsgi:application"
