[phases.setup]
nixPkgs = [
    "python311",
    "ffmpeg",
    "gcc",
    "libGL",
    "glib",
    "libSM",
    "libXext"
]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "python manage.py collectstatic --noinput || true"
]

[start]
cmd = "gunicorn myCapstone.wsgi:application"
