[phases.setup]
nixPkgs = [
    "python311Full",
    "python311Packages.pip",
    "python311Packages.setuptools",
    "python311Packages.wheel",
    "ffmpeg",
    "gcc",
    "glib",
    "libGL",
    "xorg.libX11",
    "xorg.libXext"
]

[phases.install]
cmds = [
    # Make sure Python and pip are in the PATH
    "export PATH=$(dirname $(which python3.11)):$PATH",

    # Verify pip exists
    "which pip3.11 || echo 'pip not found, trying to link manually...'",

    # Link pip globally if needed
    "ln -sf $(dirname $(which python3.11))/pip3.11 /usr/local/bin/pip || true",

    # Upgrade pip/setuptools/wheel
    "python3.11 -m pip install --upgrade pip setuptools wheel",

    # Install project dependencies
    "python3.11 -m pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "python3.11 manage.py collectstatic --noinput || true"
]

[start]
cmd = "gunicorn myCapstone.wsgi:application"
