[phases.setup]
nixPkgs = [
    "python311Full",
    "ffmpeg",
    "gcc",
    "glib",
    "libGL",
    "xorg.libX11",
    "xorg.libXext"
]


[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "python manage.py collectstatic --noinput || true"
]

[start]
cmd = "gunicorn myCapstone.wsgi:application"
