# Generated by Django 5.1.3 on 2025-03-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('scientific_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('population', models.CharField(max_length=100)),
                ('class_index', models.IntegerField(unique=True)),
            ],
        ),
    ]
