# Generated by Django 5.1.3 on 2025-04-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_bird'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bird_images/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('client', 'Client')], default='client', max_length=10),
        ),
    ]
