# Generated by Django 5.1.3 on 2025-04-14 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_bird_image_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='birdphoto',
            name='bird',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.bird'),
        ),
        migrations.AlterField(
            model_name='bird',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
